title: Rapid Annotator
author:
  name: Mohamed Mokhtar
  email: rrrokhtar@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
 With Red Hen Lab’s Rapid Annotator we try to enable researchers worldwide to annotate large chunks of data in a very short period of time with least effort possible and try to get started with minimal training.

theme: jekyll-theme-dinky
markdown: kramdown
kramdown:
  parse_block_html: true
